### PR TITLE
NRT with ecflow

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds a suite definition template for running WAFS 4xdaily (`wafs_nrt.def.tmpl`)
- adds cycle specific triggers are set as follow:  00z (0335), 06z (0935), 12z (1535), and 18z (2135)
- updates the usage of `dev/ecf/setup_ecf.sh` to allow for running a single date `PDYcyc` or NRT.

Additionally, through this PR, the triggering of UPP, GCIP, GRIB jobs are determined by the existence of atm, sfc, and master files from GFS and not just the log file.  Without this, their were failures in the NRT run due to some files being copied over from primary to backup machine before others.

I started the parallel at the 12z cycle today 09/13/2024 on Dogwood.
The details are:
```bash
PACKAGEHOME: /lfs/h2/emc/eib/noscrub/rahul.mahajan/EE2/wafs.v7.0.0
COM: /lfs/h2/emc/ptmp/rahul.mahajan/wafsNRT/com/wafs/v7.0
OUTPUT: /lfs/h2/emc/stmp/rahul.mahajan/wafsNRT/output/
DATAROOT: /lfs/h2/emc/stmp/rahul.mahajan/wafsNRT/tmp/
```
Screenshot 2024-09-13 at 4 51 04 PM

I did hit some wallclock failures (UPP, GCIP jobs), but they succeeded on rewinding the jobs.  We will likely need to examine why.  The logs will be in the `output` directory above, if you wish to take a look.

### CODE REVIEW

**Comment by aerorahul** [comment]
I am getting failures in realtime runs for the 18Z gcip f003 job that have this message:
```
*************************************************************
*** WARNING !! COULD NOT FIND GLOBCOMPVIS Satellite Data  ***
*************************************************************

One or more GLOBCOMPVIS Satellite Data files are missing, including
   /lfs/h1/ops/prod/dcom/20240913/mcidas/GLOBCOMPSIR.2024091321

wafs_gcip_f003_18 will gracfully exit
```

When this job is run much later, it ran successfully.  This is seen in the timeline of this job. It ran 3 times.  The second run was immediately resubmitted upon the first failure.  The third run (success) was much after.
Screenshot 2024-09-13 at 10 05 29 PM
Is it possible that the DCOM data is not synced from primary to backup machine before the GFS data gets synced. 

This should not be a problem in operations, when DCOM and GFS data are on the same primary machine at the same time.

If that is not the case, we will need a different mechanism to trigger the gcip jobs based on availability of dcom data.

**Comment by YaliMao-NOAA** [comment]
As described in /lfs/h1/ops/prod/packages/gfs.v16.3.17/ecf/defs/gfs_v16_3.def, except GRIB1 is triggered by GFS data itself, other jobs have time trigger:
gcip:  04:40
others: 4:30

**Comment by aerorahul** [comment]
Thanks @YaliMao-NOAA 
It wasn't really clear or explained anywhere, why that time trigger exists and for what purpose.
The WAFS EE2 kickoff slide [6, 7](https://docs.google.com/presentation/d/1yhdTfTHoBvV7K6jR2nfvkNAWn_eDJ2lTvDueRp9C89w/edit#slide=id.g158413ee633_0_116) just has this information:
Screenshot 2024-09-15 at 11 26 55 PM
The release notes should capture this information, as well as the manual in the ecf script should note this.

**Comment by aerorahul** [comment]
Till this morning's 06z, the realtime was running with a 1 day offset; i.e `PDY=PDYm1` to compensate for the failures in `GCIP` jobs.  
This is now reverted, and the GCIP jobs will be triggered at the appropriate time. (`0440` for 00z cycle).  It is not clear if the GCIP data will be available on the `backup` system at this time.  If it is not, `0440` will need to be deferred further.
`12z` run will be monitored and reported in this PR.

**Comment by aerorahul** [comment]
The 12z realtime run left a message in 
`wafsNRT/com/wafs/v7.0/wafs.20240916/12/grib2/0p25/blending/wmo/wifs_0p25_admin_msg` as
```****0000000494****
NOXX10 KKCI 161200
WAFC WASHINGTON ADVISES ALL USERS OF CB CLOUD, ICING AND TURBULENCE WAFS FORECASTS IN GRIB2 FORMAT AT 0.25 DEGREE THAT PRODUCTION PROBLEMS HAVE TRIGGERED CONTINGENCY MEASURES AND THE ISSUANCE OF NON-HARMONIZED FORECASTS.

STANDARD WAFS FORECAST PARAMETERS IN GRIB2 FORMAT (WIND, TEMPERATURE, HUMIDITY, TROP HEIGHT, MAX WIND, MAX WIND HEIGHT) ARE UNAFFECTED, AND ARE AVAILABLE AS NORMAL.

WAFC WASHINGTON APOLOGIZES FOR ANY INCONVENIENCE CAUSED DUE TO THIS ISSUE.
```
This happened because:
` /lfs/h1/ops/dev/dcom/test/20240916/wgrbbul/ukmet_wafs/egrr_wafshzds_unblended_turb_0p25_2024-09-16T12:00Z_t030.grib2` was not found in the runtime of the blending job `wafs_grib2_0p25_blending_f030_12.o189606243`

I checked for the above file on the `primary` machine, and it was not present there either.

**Comment by YaliMao-NOAA** [comment]
@aerorahul I didn't really know ecflow before you taught me. I am adding time trigger to the kickout slides, may you please let me your thoughts for UPP and grib1? Does the manager need a time trigger too?
https://docs.google.com/presentation/d/1yhdTfTHoBvV7K6jR2nfvkNAWn_eDJ2lTvDueRp9C89w/edit#slide=id.g2eeab8aa817_0_0

**Comment by YaliMao-NOAA** [comment]
Please count in time trigger. The blending process should start at T+4:30, plus 25 minutes of waiting time, it won't quit waiting till T+4:55. Now it's 16:45, T+4:45 for 12z.

> The 12z realtime run left a message in `wafsNRT/com/wafs/v7.0/wafs.20240916/12/grib2/0p25/blending/wmo/wifs_0p25_admin_msg` as
> 
> ```
> NOXX10 KKCI 161200
> WAFC WASHINGTON ADVISES ALL USERS OF CB CLOUD, ICING AND TURBULENCE WAFS FORECASTS IN GRIB2 FORMAT AT 0.25 DEGREE THAT PRODUCTION PROBLEMS HAVE TRIGGERED CONTINGENCY MEASURES AND THE ISSUANCE OF NON-HARMONIZED FORECASTS.
> 
> STANDARD WAFS FORECAST PARAMETERS IN GRIB2 FORMAT (WIND, TEMPERATURE, HUMIDITY, TROP HEIGHT, MAX WIND, MAX WIND HEIGHT) ARE UNAFFECTED, AND ARE AVAILABLE AS NORMAL.
> 
> WAFC WASHINGTON APOLOGIZES FOR ANY INCONVENIENCE CAUSED DUE TO THIS ISSUE.
> ```
> 
> This happened because: ` /lfs/h1/ops/dev/dcom/test/20240916/wgrbbul/ukmet_wafs/egrr_wafshzds_unblended_turb_0p25_2024-09-16T12:00Z_t030.grib2` was not found in the runtime of the blending job `wafs_grib2_0p25_blending_f030_12.o189606243`
> 
> I checked for the above file on the `primary` machine, and it was not present there either.

**Comment by aerorahul** [comment]
The 12z cycle finished with the above noted exceptions.
I will now shut down the near realtime parallel as it has served its purpose.

The new information about triggers timings should be addressed in a separate PR.

**Comment by aerorahul** [comment]
A capture of the 12z completion
Screenshot 2024-09-16 at 12 55 26 PM

The run details are captured in the PR description for paths to the package, output and com.

**Comment by aerorahul** [comment]
> @aerorahul I didn't really know ecflow before you taught me. I am adding time trigger to the kickout slides, may you please let me your thoughts for UPP and grib1? Does the manager need a time trigger too? https://docs.google.com/presentation/d/1yhdTfTHoBvV7K6jR2nfvkNAWn_eDJ2lTvDueRp9C89w/edit#slide=id.g2eeab8aa817_0_0

The `WAFS_GFS_MANAGER` does not need a time trigger in ops (The time trigger is added for NRT because we cannot connect to the operational ecflow suite).  In ops, it will be triggered based on `JGFS_FORECAST` job.
The `WAFS_UPP` and `WAFS_GRIB` jobs do not need time triggers.  They are released based on `WAFS_GFS_MANAGER` job
The `WAFS_GCIP` job is released by an event trigger from `WAFS_GFS_MANAGER` AND a time trigger (time trigger has been added to account for the data from DCOM to arrive).
`WAFS_GRIB2_1P25` does not need a time trigger. It is triggered based on `WAFS_UPP`
`WAFS_GRIB2_0P25` does not need a time trigger. It is triggered based on `WAFS_UPP`
`WAFS_GRIB2_0P25_BLENDING` may need a time trigger to account for data arriving from UK in addition to being triggered based on the status of `WAFS_GRIB2_0P25`

**Comment by aerorahul** [comment]
@YaliMao-NOAA 
I added the blending time trigger based on the updated EE2 kickoff slide.

**Comment by YaliMao-NOAA** [comment]
Sorry  I didn't see you are going to open a new PR to address time trigger. I am merging this PR.
> The 12z cycle finished with the above noted exceptions. I will now shut down the near realtime parallel as it has served its purpose.
> 
> The new information about triggers timings should be addressed in a separate PR.

**Pull request merged**
