### PR TITLE
Add upp as a submodule

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds [UPP](https://github.com/NOAA-EMC/UPP) as a submodule.
- adds a script to build standalone UPP with GTG
- moves build scripts from ush to sorc as NCO would like it to be
- puts executables in the EE2 vertical structure
- updates README to clone recursively and build all (upp and wafs executables)

The checkout and build was tested on WCOSS2.

### CODE REVIEW

**Comment by YaliMao-NOAA** [comment]
@aerorahul Thank you very much for the great help. I have a few questions.
1. Does it look good to mix build scripts and wafs run scripts in the same ush folder? Any suggestion to differentiate them?
2. I still think it's a good idea to separate a checkout (or install) script from the build script. Here are my reasons.
- Though I can clone upp code using 'recursive' option at the very first step, gtg code can not be cloned. gtg code is cloned by the build_upp script. If one checkout (or install) script is created, we can clone upp code then gtg code step by step in one script.
- In the build_upp script, we don't need to clone gtg code every time. When either UPP or GTG code is modified, build_upp should just compile the code, not involve cloning code.
3. If you agree with my proposal of a separate checkout script, in readme, remove the recursive clone line and add this checkout script instead.

I can do option 2 as the above on my own after I merge your PR.

**Comment by aerorahul** [comment]
> @aerorahul Thank you very much for the great help. I have a couple questions.
> 
> 1. Does it look good to mix build scripts and wafs run scripts in the same ush folder? Any suggestion to differentiate them?

There are no build scripts in `ush/` `detect_machine.sh` and `module-setup.sh` are acceptable in `ush/`.

> 2. I still think it's a good idea to separate checkout script from build script. Here are my reasons.
> 
> * Though I can clone upp to wafs using 'recursive' option at the very first step, gtg code can not be cloned. From build_upp, I see gtg code is checked out. If one checkout script is created, we can simply clone the inventory, cd the folder, run the checkout script which clones upp code then gtg code step by step.
> * In the build_upp script, we don't need to clone gtg code every time. When either UPP or GTG code is modified, build_upp should just compile the code, not involve cloning code.

It is up to you to on how you wish to set this up.

> 
> 3. If you agree with my proposal of a separate checkout script, in readme, remove the recursive clone line and add this checkout script instead.
> 
> I can do option 2 as the above on my own after I merge your PR.

Sounds good!

**Comment by YaliMao-NOAA** [comment]
I mean both detect_machine.sh and module-setup.sh are not related to the actual WAFS product run.

> There are no build scripts in `ush/` `detect_machine.sh` and `module-setup.sh` are acceptable in `ush/`.

**Comment by aerorahul** [comment]
> I mean both detect_machine.sh and module-setup.sh are not related to the actual WAFS product run.
> 
> > There are no build scripts in `ush/` `detect_machine.sh` and `module-setup.sh` are acceptable in `ush/`.

They are scripts used in the WAFS application to build and are acceptable in `ush/`.  If you remove them, then feel free to adjust as necessary.

**Pull request merged**
